### PR TITLE
Digger Nerfs, New Damage Types

### PR DESCRIPTION
**Pull request by EjoThims**
**Weapons**

Digger Nerfs - current is outright better than Ravagers, despite being a tier lower. Also some more changes to differentiate the Turret from the Gun versions, since the weight is so similar.

Both require more energy, and do less damage, but keep the small disruption. Turret turns a bit slower, and has even higher inaccuracy. Gun is even shorter range, but virtually no inaccuracy now, and slightly less energy and heat usage, all of which should help solidify it as solely a fighter and miner weapon.

Added mining laser changes from Revamp as well.

I know mining lasers as is in Revamp aren't likely to make it into vanilla, but they -might- be for the Korath versions. And I figured that having it included here would make an easier transition for these into revamp even if not.

Added corrosion damage to shunt strike in exchange for some hull damage and firestorm as an outright buff.
Added burning damage to firelance, firestorm, and inferno, in exchange for some heat damage.

All of these should be a bit stronger over time, but less powerful on immediate impact.

### CODE REVIEW

**Comment by EjoThims** [comment]
Looks like proper syntax is "burn" not "burning."

Also nerfed it, especially on firelance and inferno, because it stacks up pretty insane with a beam.

**Comment by Zitchas** [comment]
Hmmm... errors... Seems there's a mention of `" Hai "` somewhere.

**Comment by EjoThims** [comment]
> Hmmm... errors... Seems there's a mention of `" Hai "` somewhere.

No idea, it's not in any of the changes here.

**Comment by Zitchas** [comment]
Agreed. I think it's in the base branch, a holdover from back when we used those tricks.

**Review by Zitchas — DISMISSED** [review]
Sorry it took me so long to get to this. Looks good, with the sole change being to comment out the `miner 1` tag as the game won't currently recognize that.

**Pull request merged**
