### PR TITLE
reverse thusters are a manufacturer special, not common

### PR DESCRIPTION
**Pull request by ravenshining**
I mean I'm all for making reverse thrusters more widely available, but if we're going to do that we should do it for the plasma and atomics, too.

### CODE REVIEW

**Review by arkhne — APPROVED** [review]

**Comment by arkhne** [comment]
If it helps save you time, Zitchas. I checked. This change is consistent, and appears to be without typoes.

**Comment by Zitchas** [comment]
Yes, @arkhne , reviews verifying consistency and lack of typoes is definitely helpful.

**Comment by Zitchas** [comment]
The reason I had the ionic in the "common" is because, well, all the reverse thrusters are *literally* the smallest engine of its family, stuck in backwards. The stats are completely identical. So I didn't see much reason to not have it for sale anywhere that the smallest engine of its family is for sale. 

That being said, if people want it to be a little less common, sure, I'm good with this.

**Comment by ravenshining** [comment]
Right, I understand, and in principle I agree.  However, the same can be said for the Capybara and the atomic reverser, and the atomic reverser is *not* sold everywhere atomic engines are sold.  I would be fully on board with making all three more widely available, though I would prefer a difference in which one is available depending on where you are in the galaxy, which the "common" category does not facilitate.

**Pull request merged**
